# Generated by Django 4.0.4 on 2022-06-27 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_owner_alter_project_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='follow_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='icon_skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='assets/bariloche.jpg', upload_to=projects.models.user_dir_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('skills', models.ManyToManyField(blank=True, related_name='groups', to='projects.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
