# Generated by Django 4.0.4 on 2022-06-29 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_skill_category_remove_user_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(upload_to='icon_skills', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg', 'bmp', 'jpeg', 'ico', 'webp'])]),
        ),
    ]
